version: '3.7'

services:
    server:
        build: .
        restart: unless-stopped
        environment:
            NODE_ENV: production
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: postgres
            DB_PASSWORD: postgres
            PORT: '8080'
        ports:
            - '8080:8080'
        depends_on:
            - postgres
    postgres:
        image: postgres:14.3
        restart: unless-stopped
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
        driver: local
